import json
import re

payload_path = '/Users/pittipraveen/Downloads/company/techxr/Content-Population-Automation/Mantra-Aur_audio_automation/new-tracks-payload-deduped.json'
map_path = '/Users/pittipraveen/Downloads/company/techxr/Content-Population-Automation/Mantra-Aur_audio_automation/corrected_tags_map.json'

with open(payload_path, 'r', encoding='utf-8') as f:
    data = json.load(f)

with open(map_path, 'r', encoding='utf-8') as f:
    corrected_tags_map = json.load(f)

def get_yt_id(url):
    m = re.search(r'(?:v=|youtu\.be/|shorts/)([^&?\s]+)', url)
    return m.group(1) if m else url

# Set of all valid tags that can possibly be generated by Sheet1.tsv logic
ALL_TSV_TAGS = {
    "Shivji", "HanumanJi", "GaneshJi", "VishnuJi", "LakshmiJi", "ShaniiDevJi", 
    "Ramji", "KrishnaJi", "DurjaJi", "Mantra", "Strotam", "Chalisa", "Ashtakam", 
    "Stuti", "Aarti", "Shloka", "Bhajan", "Katha", "SubahUthteHi", "NahaneKeSamay", 
    "NahaneKeBaad", "BhojanSePehle", "BhojanKeBaad", "PoojaKeSamay", "PoojaKeBaad", 
    "SoneSePehle", "Peace", "Strength", "Knowledge", "Wealth", "LoveAndRelationship", 
    "Happiness", "Health", "Success", "Diwali", "Janmashtami", "Dussehra", 
    "MahaShivratri", "GaneshChaturthi", "RamNavami", "HanumanJayanti"
}

updated_count = 0

for item in data:
    opts = item.get('streamingOptions', [])
    if not opts: continue
    url = opts[0].get('contentUrl', '')
    yt_id = get_yt_id(url)
    
    if yt_id in corrected_tags_map:
        current_tags = item.get('tags', [])
        
        # Preserve tags that were statically assigned out of band
        preserved_tags = [t for t in current_tags if t not in ALL_TSV_TAGS]
        
        # New correct TSV tags
        correct_tsv_tags = corrected_tags_map[yt_id]
        
        # Combine and deduplicate, sort alphabetically for determinism
        final_tags = sorted(list(set(preserved_tags + correct_tsv_tags)))
        
        # If there's a difference, map it and increment count
        if set(current_tags) != set(final_tags):
            item['tags'] = final_tags
            updated_count += 1

print(f"Successfully applied TSV exact tags. Updated {updated_count} track DTOs.")

with open(payload_path, 'w', encoding='utf-8') as f:
    json.dump(data, f, indent=2, ensure_ascii=False)

print("Saved correctly to new-tracks-payload-deduped.json")
